@FinPath_Api_HostAddress = http://localhost:5077

POST {{FinPath_Api_HostAddress}}/api/v1/auth/register
Content-Type: application/json

{
  "email": "user@example.com",
  "displayName": "Yevgeniy",
  "password": "Passwordd1!"
}